# Generated by Django 3.1.3 on 2024-03-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_length', models.FloatField()),
                ('avg_sea_depth', models.FloatField()),
                ('layer_thickness', models.FloatField()),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialCrossTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_on_surface', models.FloatField()),
                ('width_on_bottom', models.FloatField()),
                ('distance_from_shore', models.FloatField()),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
        migrations.CreateModel(
            name='SourceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=1000)),
                ('source_url', models.CharField(max_length=512)),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_diff', models.FloatField()),
                ('temperature_diff_max', models.FloatField()),
                ('flow_speed', models.FloatField()),
                ('seawater_dens_diff', models.FloatField()),
                ('salinity', models.FloatField()),
                ('sea_surf_temp_min', models.FloatField()),
                ('sea_surf_temp_max_diff', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('vertical_speed', models.FloatField()),
                ('water_temp_max_out', models.FloatField()),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir', models.CharField(max_length=45)),
                ('measurment_place', models.CharField(max_length=225)),
                ('coordinate_y', models.FloatField()),
                ('latitude', models.CharField(max_length=1)),
                ('coordinate_x', models.FloatField()),
                ('longitude', models.CharField(max_length=1)),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
        migrations.CreateModel(
            name='DateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
    ]
