# Generated by Django 3.1.3 on 2024-03-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_datetable_locationtable_physictable_sourcetable_spatialcrosstable_spatialtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territorial_waters', models.CharField(max_length=45)),
                ('welling_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable')),
            ],
        ),
    ]
