# Generated by Django 3.1.3 on 2024-03-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_auto_20240311_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetable',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Duration of observation'),
        ),
        migrations.AlterField(
            model_name='datetable',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='datetable',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='datetable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='coordinate_x',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Coordinate X'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='coordinate_y',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Coordinate Y'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='measurment_place',
            field=models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='Measurment place'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='reservoir',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Reservoir'),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='flow_speed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Flow speed'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='salinity',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Salinity'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='sea_surf_temp_max_diff',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Sea surf temp max diff'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='sea_surf_temp_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Sea surf temp min'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='seawater_dens_diff',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Seawater dens diff'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='temperature_diff',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Temperature diff'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='temperature_diff_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Temparature diff max'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='vertical_speed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Vertical speed'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='water_temp_max_out',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Water temp max out'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='physictable',
            name='wind_speed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Wind speed'),
        ),
        migrations.AlterField(
            model_name='sourcetable',
            name='source_title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Source title'),
        ),
        migrations.AlterField(
            model_name='sourcetable',
            name='source_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='sourcetable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='spatialcrosstable',
            name='distance_from_shore',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Distance from shore'),
        ),
        migrations.AlterField(
            model_name='spatialcrosstable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='spatialcrosstable',
            name='width_on_bottom',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Width on bottom'),
        ),
        migrations.AlterField(
            model_name='spatialcrosstable',
            name='width_on_surface',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Width on surface'),
        ),
        migrations.AlterField(
            model_name='spatialtable',
            name='avg_sea_depth',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Avg sea depth'),
        ),
        migrations.AlterField(
            model_name='spatialtable',
            name='layer_thickness',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Layer thickness'),
        ),
        migrations.AlterField(
            model_name='spatialtable',
            name='strip_length',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Strip length'),
        ),
        migrations.AlterField(
            model_name='spatialtable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='territorialtable',
            name='territorial_waters',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Territorial waters'),
        ),
        migrations.AlterField(
            model_name='territorialtable',
            name='welling_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.wellingtable', verbose_name='WellingTableFK'),
        ),
        migrations.AlterField(
            model_name='wellingtable',
            name='type_welling',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Welling type'),
        ),
    ]
